general {colors = true interval = 1}
order += "ethernet _first_"
order += "wireless _first_"
order += "cpu_temperature 0"
order += "cpu_usage"
order += "load"
order += "memory"
# order += "battery 0"
order += "volume master"
order += "tztime local"

ethernet _first_ {format_up = " E: %ip (%speed) " format_down = " E: down "}
wireless _first_ {format_up = " W: %essid %ip (%quality) " format_down = " W: down "}
cpu_temperature 0 {format = " CPU %degrees °C " path = "/sys/class/hwmon/hwmon2/temp1_input" }
cpu_usage {format = " CPU: %usage "}
load {format = " load: %1min "}
memory {format = " mem: %used "}
# battery 0 {format = " %percentage %remaining " path = "/sys/class/power_supply/BAT%d/uevent"}
volume master {format = " ♪ %volume " format_muted = " muted (%volume) " device = "default"}
tztime local {format = " %d.%m.%Y | %H:%M:%S "}
